/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/the-wire',
        'architecture/layout-and-yoga',
        'architecture/parity',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/overview',
        // GENERATED, never committed (8.4 design decision 3). xmldoc2md writes
        // docs/components/reference/ from BlazorNative.Components' XML docs on
        // every site build (package.json's `prebuild`), and .gitignore keeps it
        // out of the repo: the `///` next to the code is the one home for those
        // facts, and a committed copy here would be a second one.
        //
        // `autogenerated` is what lets that directory have no roster — the
        // sidebar discovers whatever the generator emitted. A hand-listed set of
        // 26 reference pages would be a roster that has to be remembered, which
        // is the failure class this whole site is built to refuse.
        //
        // (26 = the assembly's public types — 15 concrete components, the rest
        // enums and helpers — measured, and the exact set Pin 1 holds the
        // generator to. This comment said "21", a number true of no count here:
        // a stale fact inside the rule against stale facts, 8.4 review S1-3.
        // Nothing depended on it, which is why it survived.)
        {
          type: 'category',
          label: 'Reference',
          link: { type: 'doc', id: 'components/reference/index' },
          items: [{ type: 'autogenerated', dirName: 'components/reference' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Shells',
      items: [
        'shells/android',
        'shells/ios',
      ],
    },
    'analyzers',
    'api-stability',
    'contributing',
  ],
};

export default sidebars;
